### ISSUE TITLE
Custom script fails on build

### ISSUE THREAD

**Issue by cliftonz1** [johnno1962/HotReloading#40]
On the Swift-UI example I get the following error from the custom script.

/Users/mobiledev/Library/Developer/Xcode/DerivedData/SwiftUI_Kit-amdktjtsrlmmqvegotnwvbfufrky/SourcePackages/checkouts/HotReloading/Sources/HotReloadingGuts/ClientBoot.mm:14:9: fatal error: 'XCTest/XCTest.h' file not found
#import <XCTest/XCTest.h>

<img width="1623" alt="image" src="https://user-images.githubusercontent.com/59747612/156871000-5841f26c-d76b-4e44-9552-ffb4f5ec2be7.png">

I am also getting the following warnings when building hotreload:
<img width="889" alt="image" src="https://user-images.githubusercontent.com/59747612/156870948-9508b4d7-b109-437e-844b-d046c520827d.png">

and the following error for IOS:
<img width="437" alt="image" src="https://user-images.githubusercontent.com/59747612/156870979-765ca217-a4a6-430d-a6bf-95f4e928ed54.png">

**Comment by johnno1962** [comment]
Hi, not much I can do about the warnings unfortunately but I have pushed an update to https://github.com/johnno1962/SwiftUI-Kit to use the main branch of the HotReloading repo which would be a better starting point. I've never seen this error before. What version of Xcode is this? Is your `xcode-select` path set correctly?

**Comment by cliftonz1** [comment]
I am using Xcode 13.2.1 (13C100).
And my xcode-select path is:
/Library/Developer/CommandLineTools

However, It looks like I did not have command line tools set correctly in xcode and this seemed to fix my error. 

I am still getting the warnings mentioned above.

Thank you for your assistance.
